#Deep U-Net with batch normalization model
def deep_unet(input_size=(PATCH_SIZE, PATCH_SIZE, 3)):
    inputs = layers.Input(input_size)

    # Encoder
    c1 = layers.Conv2D(64, 3, padding='same')(inputs)
    c1 = layers.BatchNormalization()(c1)
    c1 = layers.Activation('relu')(c1)
    c1 = layers.Conv2D(64, 3, padding='same')(c1)
    c1 = layers.BatchNormalization()(c1)
    c1 = layers.Activation('relu')(c1)
    p1 = layers.MaxPooling2D()(c1)

    c2 = layers.Conv2D(128, 3, padding='same')(p1)
    c2 = layers.BatchNormalization()(c2)
    c2 = layers.Activation('relu')(c2)
    c2 = layers.Conv2D(128, 3, padding='same')(c2)
    c2 = layers.BatchNormalization()(c2)
    c2 = layers.Activation('relu')(c2)
    p2 = layers.MaxPooling2D()(c2)

    c3 = layers.Conv2D(256, 3, padding='same')(p2)
    c3 = layers.BatchNormalization()(c3)
    c3 = layers.Activation('relu')(c3)
    c3 = layers.Conv2D(256, 3, padding='same')(c3)
    c3 = layers.BatchNormalization()(c3)
    c3 = layers.Activation('relu')(c3)
    p3 = layers.MaxPooling2D()(c3)

    c4 = layers.Conv2D(512, 3, padding='same')(p3)
    c4 = layers.BatchNormalization()(c4)
    c4 = layers.Activation('relu')(c4)
    c4 = layers.Conv2D(512, 3, padding='same')(c4)
    c4 = layers.BatchNormalization()(c4)
    c4 = layers.Activation('relu')(c4)
    p4 = layers.MaxPooling2D()(c4)

    c5 = layers.Conv2D(1024, 3, padding='same')(p4)
    c5 = layers.BatchNormalization()(c5)
    c5 = layers.Activation('relu')(c5)
    c5 = layers.Conv2D(1024, 3, padding='same')(c5)
    c5 = layers.BatchNormalization()(c5)
    c5 = layers.Activation('relu')(c5)
    p5 = layers.MaxPooling2D()(c5)

    # Bottleneck
    c6 = layers.Conv2D(2048, 3, padding='same')(p5)
    c6 = layers.BatchNormalization()(c6)
    c6 = layers.Activation('relu')(c6)
    c6 = layers.Conv2D(2048, 3, padding='same')(c6)
    c6 = layers.BatchNormalization()(c6)
    c6 = layers.Activation('relu')(c6)

    # Decoder
    u7 = layers.UpSampling2D()(c6)
    u7 = layers.concatenate([u7, c5])
    c7 = layers.Conv2D(1024, 3, padding='same')(u7)
    c7 = layers.BatchNormalization()(c7)
    c7 = layers.Activation('relu')(c7)
    c7 = layers.Conv2D(1024, 3, padding='same')(c7)
    c7 = layers.BatchNormalization()(c7)
    c7 = layers.Activation('relu')(c7)

    u8 = layers.UpSampling2D()(c7)
    u8 = layers.concatenate([u8, c4])
    c8 = layers.Conv2D(512, 3, padding='same')(u8)
    c8 = layers.BatchNormalization()(c8)
    c8 = layers.Activation('relu')(c8)
    c8 = layers.Conv2D(512, 3, padding='same')(c8)
    c8 = layers.BatchNormalization()(c8)
    c8 = layers.Activation('relu')(c8)

    u9 = layers.UpSampling2D()(c8)
    u9 = layers.concatenate([u9, c3])
    c9 = layers.Conv2D(256, 3, padding='same')(u9)
    c9 = layers.BatchNormalization()(c9)
    c9 = layers.Activation('relu')(c9)
    c9 = layers.Conv2D(256, 3, padding='same')(c9)
    c9 = layers.BatchNormalization()(c9)
    c9 = layers.Activation('relu')(c9)

    u10 = layers.UpSampling2D()(c9)
    u10 = layers.concatenate([u10, c2])
    c10 = layers.Conv2D(128, 3, padding='same')(u10)
    c10 = layers.BatchNormalization()(c10)
    c10 = layers.Activation('relu')(c10)
    c10 = layers.Conv2D(128, 3, padding='same')(c10)
    c10 = layers.BatchNormalization()(c10)
    c10 = layers.Activation('relu')(c10)

    u11 = layers.UpSampling2D()(c10)
    u11 = layers.concatenate([u11, c1])
    c11 = layers.Conv2D(64, 3, padding='same')(u11)
    c11 = layers.BatchNormalization()(c11)
    c11 = layers.Activation('relu')(c11)
    c11 = layers.Conv2D(64, 3, padding='same')(c11)
    c11 = layers.BatchNormalization()(c11)
    c11 = layers.Activation('relu')(c11)

    outputs = layers.Conv2D(1, 1, activation='sigmoid')(c11)

    return Model(inputs, outputs)
